### ISSUE TITLE
Guardar timezone en Occurrence

### ISSUE THREAD

**Issue by Rombusevil** [MagmaPlayout/mp-playout-api#2]
El campo startDateTime de la tabla Occurrence se guarda con la hora local pero representada como UTC.
Por ejemplo, si programo con el calendario un clip a las 12:47 GMT-3, en la tabla occurrence se guarda:
2017-08-20T12:47:00.000Z y debería ser 2017-08-20T12:51:51-03:00Z (donde el -03:00Z es el timezone del cliente y no estoy seguro si la Z ahí es necesaria, entiendo que sí)

En el core lo voy a patchear momentaneamente para que funcione como está ahora. Cuando se haga este cambio descomento el core para que lo interprete bien

**Comment by Rombusevil** [comment]
El core ahora asume que el TS está correcto, así que se rompió la integración con el sistema hasta que se arregle este bug (me estaba confundiendo trabajar con el workaround)

**Comment by luism88** [comment]
@Rombusevil ya funciona. Solo había que agregar el timezone al fullcalendar.

timezone : 'local'
